@startuml
title Modelo de Clases - Gestión de Parqueadero

abstract class Usuario {
  - id: UUID
  - nombre: String
  - cedula: String
  + rol(): Rol
}
class Cliente
class Operador
class Gerente

enum Rol {
  CLIENTE
  OPERADOR
  GERENTE
}

class Vehiculo {
  - placa: String
}
class TipoVehiculo {
  - nombre: String
  - descripcion: String
}
class Tarifa {
  - valorHora: BigDecimal
  - anioVigencia: int
}
class RegistroIngreso {
  - horaEntrada: LocalDateTime
  - horaSalida: LocalDateTime
}
class Pago {
  - valor: BigDecimal
  - fechaPago: LocalDateTime
  - pagado: boolean
}

Cliente -up-|> Usuario
Operador -up-|> Usuario
Gerente -up-|> Usuario
Usuario ..> Rol

Cliente "0..1" --o "*" Vehiculo : "es dueño de"
Vehiculo "*" -- "1" TipoVehiculo : "es de tipo"
TipoVehiculo "1" -- "*" Tarifa : "tiene tarifa"
Vehiculo "1" -right- "*" RegistroIngreso : "realiza"
Operador "0..1" --o "*" RegistroIngreso : "autoriza"
RegistroIngreso "1" -- "0..1" Pago : "posee"

@enduml
