@startuml
title Diagrama de Paquetes - Arquitectura por Capas
skinparam linetype ortho
skinparam packageStyle rectangle

package "Presentacion (controller)" {
  [LoginController]
  [LogoutController]
  [RegistroController]
  [DentroController]
  [RegistroIngresoController]
  [PagoController]
  [TarifaController]
  [VehiculoController]
  [ClienteController]
  [OperadorController]
  [GerenteController]
  [TipoVehiculoController]
  [MiCuentaController]
  [MiPerfilController]
  [FiltroAutenticacion]
}

package "Servicio (services)" {
  [TarifaService]
  [RegistroIngresoService]
  [PagoService]
  [VehiculoService]
  [ClienteService]
  [OperadorService]
  [GerenteService]
  [TipoVehiculoService]
  [PerfilService]
}

package "Persistencia (persistence)" {
  [UsuarioRepository]
  [VehiculoRepository]
  [TipoVehiculoRepository]
  [RepositorioTarifa]
  [RepositorioRegistroIngreso]
  [RepositorioPago]
  [DB]
  [PasswordHasher]
}

package "Modelo (model)" {
  [Usuario]
  [Cliente]
  [Operador]
  [Gerente]
  [Rol]
  [Vehiculo]
  [TipoVehiculo]
  [Tarifa]
  [RegistroIngreso]
  [Pago]
  [MovimientoCliente]
  [VehiculoDentro]
}

package "Transversal (util)" {
  [Formato]
  [PasswordPolicy]
}

"Presentacion (controller)" --> "Servicio (services)"
"Presentacion (controller)" --> "Modelo (model)"
"Presentacion (controller)" --> "Transversal (util)"
"Servicio (services)" --> "Persistencia (persistence)"
"Servicio (services)" --> "Modelo (model)"
"Servicio (services)" --> "Transversal (util)"
"Persistencia (persistence)" --> "Modelo (model)"
@enduml
