@startuml
title Diagrama de Paquetes - Gestión de Parqueadero
skinparam linetype ortho

package "Presentación (controller)" {
  [LoginController]
  [DentroController]
  [RegistroIngresoController]
  [PagoController]
  [TarifaController]
  [VehiculoController]
  [ClienteController]
  [OperadorController]
  [GerenteController]
  [TipoVehiculoController]
  [MiCuentaController]
  [FiltroAutenticacion]
}

package "Servicio (services)" {
  [TarifaService]
  [RegistroIngresoService]
  [PagoService]
  [VehiculoService]
  [ClienteService]
  [OperadorService]
  [GerenteService]
  [TipoVehiculoService]
}

package "Persistencia (persistence)" {
  [UsuarioRepository]
  [VehiculoRepository]
  [TipoVehiculoRepository]
  [RepositorioTarifa]
  [RepositorioRegistroIngreso]
  [RepositorioPago]
  [DB]
  [PasswordHasher]
}

package "Modelo (model)" {
  [Usuario]
  [Cliente]
  [Operador]
  [Gerente]
  [Rol]
  [Vehiculo]
  [TipoVehiculo]
  [Tarifa]
  [RegistroIngreso]
  [Pago]
}

"Presentación (controller)" --> "Servicio (services)"
"Presentación (controller)" --> "Modelo (model)"
"Servicio (services)" --> "Persistencia (persistence)"
"Servicio (services)" --> "Modelo (model)"
"Persistencia (persistence)" --> "Modelo (model)"
@enduml
